version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: file_uploads_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 211213058nA
      MYSQL_DATABASE: file_uploads
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
    driver: local

